urlTest01URL=http://www.google.com/
googleLogoID=hplogo
googleQueryInputBoxNM=q
googleQyeryGoogleSearchButtonNM=btnK
googleQyeryFeelingLuckyButtonID=gbqfbb
OLDgoogleQueryResultsStatsID=mBMHK
googleQueryResultsStatsID=result-stats