urlTest01URL=http://demo.guru99.com/test/guru99home/
guru99FrameID=a077aa5e
guru99FrameImageXP=/html/body/a/img
guru99linkXP=//*[@id="rt-footer"]/div[1]/div/div/div/div/div[3]/div/div/div[2]/div/a[1]

urlTest02URL=http://demo.guru99.com/test/drag_drop.html
guru99DragDropTitleCS=div.item-page
guru99DragBankButtonID=credit2
guru99DragSalesButtonID=credit1
guru99DropDebtAccountID=bank
guru99DropCredAccountID=loan