mshURL=http://mobiletest.me/iphone_5_emulator/?u=http://mashable.com
mblMobileEmulatorPageID=iphone_5_emulator
mblMobileEmulatorChildCS=.group-hover\\3Atext-secondary-300:nth-child(1)
mshBurgerMenuButtonCS=.h-7
mshTechMenuOptionCS=.mt-6:nth-child(2) > .uppercase > strong
mshCloseBurgerMenuButtonCS=.absolute > .w-6
mshMainHeadlinerCS=.lg\\3Atext-4xl
mshSearchButtonCS=.ml-2
mshSearchInputTextBoxCS=.pr-2
mshExecuteSearchButtonCS=.ml-2
mshClickResultSearchXP=//li[2]/a
mshFirstLinkCS=#firstRecommendation .mr-1
mshHeaderTextCS=.header-100
